# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clothly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for Clothly
  target 'ClothlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClothlyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
